# Generated by Django 4.2.4 on 2023-09-01 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_remove_report_upload_date_report_last_changed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Annotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("annotation", models.JSONField()),
                ("upload_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name="report",
            old_name="last_changed",
            new_name="last_updated",
        ),
        migrations.DeleteModel(
            name="Document",
        ),
        migrations.AddField(
            model_name="annotation",
            name="report",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="reports.report"
            ),
        ),
    ]
