# Generated by Django 4.2.4 on 2023-09-02 02:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0002_alter_report_file"),
        ("reports", "0004_annotation_verified"),
    ]

    operations = []
