# Generated by Django 4.2.4 on 2023-09-04 05:51

from django.db import migrations, models
import reports.models


class Migration(migrations.Migration):
    dependencies = [
        ("reports", "0005_merge_0002_alter_report_file_0004_annotation_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="file",
            field=models.FileField(
                upload_to=reports.models.file_upload_path,
                validators=[reports.models.validate_file],
            ),
        ),
    ]
